apiVersion: v1
kind: Service
metadata:
  name: {{ required "Service name should be specified!" .Values.name }}
spec:
  selector:
    app: {{ required "Service name should be specified!" .Values.name }}
  ports:
    - protocol: TCP
      port: {{ required "Service port should be specified!" .Values.port }}
      targetPort: service-port